@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.arguments;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;