@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.command.arguments.serializers;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;