@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.network.status;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;