@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.client.network.handshake;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;