@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.world.biome.provider;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;